name: "[Workflow] Main"

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: ESLint Javascript
    uses: ./.github/workflows/lint_job.yml

  test:
    name: Jest Tests
    uses: ./.github/workflows/test_job.yml

  publish_unit_tests:
    name: Publish Unit Tests
    needs: ['lint', 'test']
    uses: ./.github/workflows/publish_unit_tests_job.yml

  sonar_cloud:
    name: Sonar Cloud
    needs: ['lint', 'test']
    uses: ./.github/workflows/sonar_cloud_job.yml
    secrets:
      SONARCLOUD_SECRET: ${{ secrets.SONARCLOUD_TOKEN }}

  create_tag_publish:
    name: Bump, Tag and Publish Pre-release
    runs-on: ubuntu-latest
    needs: ['lint', 'test']
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Cache yarn dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Build Module
      run: yarn run build
