name: "[Workflow] Main"

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: ESLint Javascript
    uses: ./.github/workflows/lint_job.yml

  test:
    name: Jest Tests
    uses: ./.github/workflows/test_job.yml

  publish_unit_tests:
    name: Publish Unit Tests
    needs: ['lint', 'test']
    uses: ./.github/workflows/publish_unit_tests_job.yml

  sonar_cloud:
    name: Sonar Cloud
    needs: ['lint', 'test']
    uses: ./.github/workflows/sonar_cloud_job.yml
    secrets:
      SONARCLOUD_SECRET: ${{ secrets.SONARCLOUD_TOKEN }}

  create_tag_publish:
    name: Bump, Tag and Publish Pre-release
    runs-on: ubuntu-latest
    needs: ['lint', 'test']
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Cache yarn dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Build Module
      run: yarn run build

    - name: Bump version
      id: bump_version
      uses: anothrNick/github-tag-action@1.54.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.0
        DEFAULT_BUMP: patch
        PRERELEASE_SUFFIX: ${{ env.BRANCH_NAME }}
        RELEASE_BRANCHES: main
        WITH_V: false

    - name: Changelog
      uses: Bullrich/generate-release-changelog@2.0.1
      id: changelog
      env:
        REPO: ${{ github.repository }}

    # Create a release for this specific version
    - name: Create Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ steps.bump_version.outputs.new_tag }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.bump_version.outputs.new_tag }}
        body: ${{ steps.changelog.outputs.changelog }}
