name: pr
on: [pull_request]

jobs:
  linux:
    name: Linux build on node 16.11.1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version 16.11.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.11.1

      - name: Install packages
        run: yarn install

      - name: Run Linting
        run: yarn run lint:check

      - name: Run Tests
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Build
        run: yarn run build
